### ISSUE TITLE
Pypi publish action failed

### ISSUE THREAD

**Issue by kabeor** [aquynh/capstone#2048]
```yaml
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to PyPI
        if: ${{ success() }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_pass }}
```

According to [gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish):
*The master branch version has been sunset. Please, change the GitHub Action version you use from master to release/v1 or use an exact tag, or a full Git commit SHA.*

A fixing for [python-publish.yml](https://github.com/capstone-engine/capstone/blob/v5/.github/workflows/python-publish.yml) is needed.
