### ISSUE TITLE
Cancel previous workflows on push

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2455]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [ ] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [x] Other (elaborated below)

**Describe the feature you'd like**

Pushing to a PR which has still running workflows, doesn't stop those workflows.
This wastes a lot of our Action minutes. We should add:

```yaml
# Stop previous runs on the same branch on new push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}
```

This example would require that the release is in it's own `release/...` branch. So on the release branch nothing gets canceled.

**Additional context**

Docs: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
